experiment: low-dimensional
model: NCDSSMNL
dataset: bouncing_ball
exp_root_dir: ./results/{model}/{dataset}/{timestamp}/
train_batch_size: 50
test_batch_size: 50
learning_rate: 1.e-2
lr_decay_rate: 0.9
lr_decay_steps: 500
train_missing_p: 0.
ssm_params_warmup_steps: 0
max_grad_norm: 100.0
num_steps: 5000
log_steps: 500
save_steps: 500
device: cpu  # Which device to use, e.g., cpu, cuda:0, cuda:1, ...
z_dim: 6
y_dim: 1
u_dim: 0
aux_dim: 1
inference_trainable_cov: true
drift_mlp_units: 64
drift_hidden_layers: 1
drift_nonlinearity: softplus
drift_last_nonlinearity: false
drift_zero_init_last: false
drift_spectral_norm: false
fixed_H: true
num_forecast: 50
num_plots: 5
integration_step_size: 0.05
integration_method: rk4