experiment: pymunk
model: NCDSSMNL
dataset: box
exp_root_dir: ./results/{model}/{dataset}/{timestamp}/
train_batch_size: 32
test_batch_size: 8
learning_rate: 2.e-3
lr_decay_rate: 0.9
lr_decay_steps: 3000
train_missing_p: 0.2
ssm_params_warmup_steps: 1000
max_grad_norm: 100.0
num_steps: 100000
log_steps: 5000
save_steps: 10000
device: cuda:0  # Which device to use, e.g., cpu, cuda:0, cuda:1, ...
img_size: 32
z_dim: 10
y_dim: 1024
u_dim: 0
aux_dim: 4
inference_img_enc_dim: 64
inference_tied_cov: false
inference_trainable_cov: true
drift_mlp_units: 64
drift_hidden_layers: 1
drift_nonlinearity: tanh
drift_last_nonlinearity: true
drift_zero_init_last: true
drift_spectral_norm: false
fixed_diffusion: true
diffusion_mlp_units: 64
diffusion_hidden_layers: 1
diffusion_nonlinearity: softplus
diffusion_spectral_norm: true
fixed_H: false
num_forecast: 16
num_plots: 5
integration_step_size: 0.05
integration_method: rk4