experiment: low-dimensional
model: NCDSSMNL
dataset: mocap
exp_root_dir: ./results/{model}/{dataset}/{timestamp}/
train_batch_size: 16
test_batch_size: 4
learning_rate: 1.e-2
lr_decay_rate: 0.9
lr_decay_steps: 500
train_missing_p: 0.
ssm_params_warmup_steps: 100
max_grad_norm: 100.
num_steps: 2600
log_steps: 100
save_steps: 100
device: cpu  # Which device to use, e.g., cpu, cuda:0, cuda:1, ...
z_dim: 10
y_dim: 50
u_dim: 0
aux_dim: 6
emission_mlp_units: 30
emission_hidden_layers: 2
emission_nonlinearity: softplus
emission_tied_cov: true
emission_trainable_cov: true
concat_mask: false
inference_mlp_units: 64
inference_nonlinearity: softplus
inference_tied_cov: false
inference_trainable_cov: true
drift_mlp_units: 30
drift_hidden_layers: 1
drift_nonlinearity: softplus
drift_last_nonlinearity: false
drift_zero_init_last: false
drift_spectral_norm: true
fixed_diffusion: true
diffusion_mlp_units: 30
diffusion_hidden_layers: 1
diffusion_nonlinearity: softplus
diffusion_spectral_norm: true
fixed_H: true
num_forecast: 50
num_plots: 5
integration_step_size: 0.05
integration_method: rk4